name: Housekeeping
on: 
  push:
  schedule:
  #  Kick off job at midnight on the 1st and the 15th of every month
  - cron: "0 0 1,15 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: cd utils
        run:  |
        cd utils
      - name: run python
        run:  |
        python update_json_files.py
        cd ..
        git add .
        git config --global user.name 'Philip Wright'
        git config --global user.email 'wrightphilip4@gmail.com.github.com'
        git commit -am 'Update JSON files'
        git push